spring:
  kafka:
    consumer:
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: paymentNotification:com.yasser.ecommerce.notification.PaymentNotificationRequest,orderConfirmation:com.yasser.ecommerce.kafka.OrderConfirmation
  application:
    name: notification-service

server:
  port: 8095

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/